apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: devpi
  name: devpi
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.service: devpi
    spec:
      containers:
        - image: edxops/devpi:latest
          name: edx-devstack-devpi
          ports:
            - containerPort: 3141
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: devpi-data
      hostname: devpi-devstack-edx
      restartPolicy: Always
      volumes:
        - name: devpi-data
          persistentVolumeClaim:
            claimName: devpi-data
status: {}
