apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: ecommerce
  name: ecommerce
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.service: ecommerce
    spec:
      containers:
      - args:
        - bash
        - -c
        - source /edx/app/ecommerce/ecommerce_env && while true; do python /edx/app/ecommerce/ecommerce/manage.py
          runserver 0.0.0.0:18130; sleep 2; done
        env:
        - name: ENABLE_DJANGO_TOOLBAR
          value: "1"
        image: edxops/ecommerce:latest
        name: edx.devstack.ecommerce
        ports:
        - containerPort: 18130
        resources: {}
        stdin: true
        tty: true
      hostname: ecommerce.devstack.edx
      restartPolicy: Always
status: {}
